default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: evhiro
  password: eLN8FdqImq3ZNvJkys65SErlJwdCcnzE
  host: dpg-clmtp938772c73e1hrvg-a.singapore-postgres.render.com
  port: 5432
  database: final_capstone_c8le

development:
  <<: *default
  database: final_capstone_c8le

test:
  <<: *default
  database: final_capstone_test

production:
  <<: *default
  username: evhiro
  password: eLN8FdqImq3ZNvJkys65SErlJwdCcnzE
  host: dpg-clmtp938772c73e1hrvg-a.singapore-postgres.render.com
  port: 5432
  database: final_capstone_c8le
